import { HeroGender, HeroProfession } from "./enums";
import { HeroModel } from "./models";

export const HEROES: HeroModel[] = [
    { name: "Xatec", profession: HeroProfession.Barbarian, gender: HeroGender.Male },
    { name: "Xedax", profession: HeroProfession.Wizard, gender: HeroGender.Male },
    { name: "Jozec", profession: HeroProfession.Bard, gender: HeroGender.Male },
    { name: "Reyodir", profession: HeroProfession.Priest, gender: HeroGender.Male },
    { name: "Xetoves", profession: HeroProfession.Thief, gender: HeroGender.Male },
    { name: "Razucox", profession: HeroProfession.Barbarian, gender: HeroGender.Male },
    { name: "Rele", profession: HeroProfession.Priest, gender: HeroGender.Male },
    { name: "Fearless", profession: HeroProfession.Thief, gender: HeroGender.Male },
    { name: "Austere", profession: HeroProfession.Priest, gender: HeroGender.Male },
    { name: "Sotox", profession: HeroProfession.Thief, gender: HeroGender.Male },
    { name: "Gamoc", profession: HeroProfession.Bard, gender: HeroGender.Male },
    { name: "Zotis", profession: HeroProfession.Knight, gender: HeroGender.Male },
    { name: "Boror", profession: HeroProfession.Bard, gender: HeroGender.Male },
    { name: "Bezegot", profession: HeroProfession.Knight, gender: HeroGender.Male },
    { name: "Vilenen", profession: HeroProfession.Barbarian, gender: HeroGender.Male },
    { name: "Kodekil", profession: HeroProfession.Barbarian, gender: HeroGender.Male },
    { name: "Xigix", profession: HeroProfession.Knight, gender: HeroGender.Male },
    { name: "Blind", profession: HeroProfession.Wizard, gender: HeroGender.Male },
    { name: "Spellbound", profession: HeroProfession.Wizard, gender: HeroGender.Male },
    { name: "Jogon", profession: HeroProfession.Wizard, gender: HeroGender.Male },
    { name: "Hasua", profession: HeroProfession.Bard, gender: HeroGender.Female },
    { name: "Lymi", profession: HeroProfession.Bard, gender: HeroGender.Female },
    { name: "Mizi", profession: HeroProfession.Bard, gender: HeroGender.Female },
    { name: "Hazeke", profession: HeroProfession.Barbarian, gender: HeroGender.Female },
    { name: "Muadiky", profession: HeroProfession.Knight, gender: HeroGender.Female },
    { name: "Yreny", profession: HeroProfession.Priest, gender: HeroGender.Female },
    { name: "Kotot", profession: HeroProfession.Thief, gender: HeroGender.Female },
    { name: "Centaur", profession: HeroProfession.Priest, gender: HeroGender.Female },
    { name: "Delirious", profession: HeroProfession.Thief, gender: HeroGender.Female },
    { name: "Samar", profession: HeroProfession.Priest, gender: HeroGender.Female },
    { name: "Phema", profession: HeroProfession.Barbarian, gender: HeroGender.Female },
    { name: "Lina", profession: HeroProfession.Bard, gender: HeroGender.Female },
    { name: "Cyhy", profession: HeroProfession.Knight, gender: HeroGender.Female },
    { name: "Lyhely", profession: HeroProfession.Priest, gender: HeroGender.Female },
    { name: "Phiadasa", profession: HeroProfession.Thief, gender: HeroGender.Female },
    { name: "Deahymi", profession: HeroProfession.Wizard, gender: HeroGender.Female },
    { name: "Zaga", profession: HeroProfession.Knight, gender: HeroGender.Female },
    { name: "Fearless", profession: HeroProfession.Priest, gender: HeroGender.Female },
    { name: "Leaf", profession: HeroProfession.Thief, gender: HeroGender.Female },
    { name: "Xuvur", profession: HeroProfession.Wizard, gender: HeroGender.Female },
];